(require 'package)

(unless package-archive-contents
  (package-refresh-contents))

(mapc
 (lambda (package)
   (or (package-installed-p package)
       (package-install package)))
 '(ag
   alchemist
   anaconda-mode
   android-mode
   ant
   auto-complete
   col-highlight
   column-marker
   company
   company-anaconda
   company-c-headers
   company-ghc
   company-go
   company-inf-ruby
   company-irony
   concurrent
   crosshairs
   ctable
   darcula-theme
   deferred
   dirtree
   elixir-mix
   elixir-mode
   elixir-yasnippets
   ensime
   epc
   fill-column-indicator
   flycheck
   flycheck-haskell
   flycheck-haskell
   flycheck-irony
   flycheck-pos-tip
   flymake
   flymake-elixir
   flymake-go
   flymake-haml
   flymake-json
   flymake-python-pyflakes
   flymake-ruby
   git-rebase-mode
   git-commit-mode
   go-eldoc
   go-mode
   go-projectile
   groovy-mode
   haskell-mode
   hc-zenburn-theme
   helm
   helm-R
   helm-ag-r
   helm-aws
   helm-bibtex
   helm-c-moccur
   helm-c-yasnippet
   helm-company
   helm-dash
   helm-flycheck
   helm-ghc
   helm-git
   helm-go-package
   helm-google
   helm-open-github
   helm-package
   helm-projectile
   helm-projectile-all
   helm-pydoc
   helm-rails
   helm-rb
   hl-line+
   inf-ruby
   irony
   javadoc-lookup
   jedi
   json-mode
   magit
   markdown-mode
   matlab-mode
   nasm-mode
   popup
   projectile
   projectile-speedbar
   projectile-rails
   python-environment
   rust-mode
   sr-speedbar
   redis
   rich-minority
   rubocop
   ruby-block
   ruby-electric
   ruby-hash-syntax
   ruby-tools
   rvm
   sbt-mode
   scala-mode2
   scala-outline-popup
   snippet
   vline
   web-mode
   yaml-mode
   yasnippet
   zenburn-theme))
